name: DO CMS # (string) site's name
description:
  # (string, or map[language-code]text)
  en: Content Management System where its content is built through CI/CD pipeline
  vi: Hệ thống Quản trị nội dung với dữ liệu được xây dựng trên qui trình CI/CD
icon: fas fa-code # (string) site's icon, supporting FontAwesome icons
languages:
  # (map[language-code]text) available languages
  en: English
  vi: Tiếng Việt
  default: en # default language
contacts:
  # (map[string]string) site's contact info
  website: "https://github.com/btnguyen2k/docms"
  email: "btnguyen2k (at) gmail (dot) com"
  github: "https://github.com/btnguyen2k/"
  facebook: ""
  linkedin: "https://www.linkedin.com/in/btnguyen2k/"
  slack: ""
  twitter: ""
