title:
    en: Images
    vi: Hình ảnh
summary:
    en: Show cases how to embed images into documents.
    vi: Trình diễn cách nhúng hình ảnh vào tài liệu.
icon:
file:
    en: index-en.md
    vi: index-vi.md
tags:
    en: [demo, image]
    vi: [demo, trình diễn, hình ảnh]
tc: 1687846925
tu: 1687846925
