title:
  # (string, or map[language-code]text)
  en: DOCLI
  vi: DOCLI
summary:
  # (string, or map[language-code]text)
  en: "Pre-processing tool to check website content for errors and build fulltext index."
  vi: "Công cụ tiền xử lý kiểm tra lỗi trong nội dung trang web và xây dựng chỉ mục toàn văn (fulltext index)."
icon: # (string) supporting FontAwesome icons
file:
  # (map[language-code]filename)
  en: index-en.md
  vi: index-vi.md
tags:
  # (map[language-code]Array(string))
  en: [cli, docli, pre-processing, process]
  vi: [cli, docli, xử lý, tiền xử lý]
