title:
    en: Videos
    vi: Video
summary:
    en: Show cases how to embed videos into documents.
    vi: Trình diễn cách nhúng video vào tài liệu.
icon:
file:
    en: index-en.md
    vi: index-vi.md
tags:
    en: [demo, video]
    vi: [demo, trình diễn, video]
tc: 1687854847
tu: 1687854847
