title:
  # (string, or map[language-code]text)
  en: DO CMS Runtime
  vi: DO CMS Runtime
summary:
  # (string, or map[language-code]text)
  en: "DO CMS runtime is the main component to render the website content. It also offers other features such as i18n and fulltext search."
  vi: "DO CMS runtime là thành phần chính thể hiện nội dung trang web. Một số chức năng khác được hỗ trợ như i18n hoặc tìm kiếm toàn văn (fulltext search)."
icon: # (string) supporting FontAwesome icons
file:
  # (map[language-code]filename)
  en: index-en.md
  vi: index-vi.md
