name: docms-release

on:
  # Automatically trigger it there are changes in repo
  pull_request:
    types: [ closed ]
    branches: [ release ]

  # Allow mannually trigger 
  workflow_dispatch:

jobs:
  build_if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      - name: Setup application version number and build date
        run: |
          APP_VERSION=`jq -r '.version' ./appinfo.json`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCMS_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCMS_REGISTRY_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            btnguyen2k/docmsruntime:${{ env.APP_VERSION }}
            btnguyen2k/docmsruntime:stable
          file: ./Dockerfile.cms
          context: ./
