name: docms

on:
  # Automatically trigger it there are changes in repo
  push:
    branches: [ cms ]
    paths:
    - '**'
    - '.github/workflows/docms.yml'

  # Allow mannually trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      - name: Setup application version number and build date
        run: |
          APP_VERSION=`jq -r '.version' ./appinfo.json`
          echo "APP_VERSION=$APP_VERSION" >> $GITHUB_ENV
          BUILD_DATE=`date +%Y%m%d`
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCMS_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCMS_REGISTRY_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            btnguyen2k/docmsruntime:${{ env.BUILD_DATE }}-${{ github.sha }}
            btnguyen2k/docmsruntime:latest
          file: ./Dockerfile.cms
          context: ./
