name: dodocs

on:
  # Automatically trigger it there are changes in repo
  push:
    branches: [ docs ]
    paths:
    - 'dosrc/**'
    - '.github/workflows/dodocs.yml'
    - 'Dockerfile.docs'
    - 'go.mod'

  # Allow mannually trigger 
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      BUILD_DATE: ${{ steps.setenv.outputs.BUILD_DATE }}
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2
      - name: Setup build date
        id: setenv
        run: |
          BUILD_DATE=`date +%Y%m%d`
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_ENV
          echo "BUILD_DATE=$BUILD_DATE" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: docker.io
          username: ${{ secrets.DOCMS_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCMS_REGISTRY_PASSWORD }}
      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            btnguyen2k/docmsdocs:${{ env.BUILD_DATE }}-${{ github.sha }}
            btnguyen2k/docmsdocs:latest
          file: ./Dockerfile.docs
          context: ./

  deploy:
    runs-on: ubuntu-latest
    needs: build
    env:
      BUILD_DATE: ${{needs.build.outputs.BUILD_DATE}}
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.DOCMS_AZURE_CREDENTIALS }}
      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp update \
              --subscription "${{ secrets.DOCMS_AZURE_SUBSCRIPTION_ID }}" \
              --name "${{ secrets.DOCMS_AZURE_CONTAINERAPP_NAME }}" \
              --resource-group "${{ secrets.DOCMS_AZURE_CONTAINERAPP_RG }}" \
              --container-name "${{ secrets.DOCMS_AZURE_CONTAINERAPP_CONTAINER_NAME }}" \
              --image "docker.io/${{ secrets.DOCMS_REGISTRY_USERNAME }}/docmsdocs:$BUILD_DATE-${{ github.sha }}"
